name: Fetch and Update PacketsDatabase Data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      # Step 1: Fetch the data
      - name: Fetch and process data
        run: | # <-- FIX: Added pipe for multi-line script
          echo "Starting data fetch from packetsdatabase.com..."
          API_URL="https://packetsdatabase.com/api/data"
          TOTAL_COUNT=$(curl -s -L "${API_URL}?page=1&size=1&filter=" | jq -r '.total')
          if ! [[ "$TOTAL_COUNT" =~ ^[0-9]+$ ]] || [ "$TOTAL_COUNT" -le 0 ]; then
            echo "Error: Failed to retrieve a valid total count."
            exit 1
          fi
          echo "Total records to fetch: $TOTAL_COUNT"
          curl -s --connect-timeout 60 --max-time 300 -L "${API_URL}?page=1&size=${TOTAL_COUNT}&filter=" -o data.json
          if [ ! -s data.json ]; then
             echo "Error: Failed to download the full dataset."
             exit 1
          fi
          echo "Full dataset downloaded."

      # Step 2: Generate all file formats
      - name: Generate Lists and Formats
        run: | # <-- FIX: Added pipe for multi-line script
          echo "Generating all file formats..."
          jq -r '.data[][1]' data.json > ip_list.txt
          echo "Generated ip_list.txt"
          echo "IP,Port,Protocol,Country,ASN,Organization,ISP" > full_data.csv
          jq -r '.data[] | [.[1], .[2], .[7], .[9], .[10], .[11], .[12]] | @csv' data.json >> full_data.csv
          echo "Generated full_data.csv"
          jq -c '.data[] | {ip: .[1], port: .[2], protocol: .[7], country: .[9], asn: .[10], organization: .[11], isp: .[12]}' data.json > full_data.jsonl
          echo "Generated full_data.jsonl"
          jq -r '.data[][1] | "deny \(.);"' data.json > nginx_blocklist.conf
          echo "Generated nginx_blocklist.conf"
          echo '#!/bin/bash' > iptables_blocklist.sh
          echo '# This script will add all IPs from the list to your iptables DROP chain.' >> iptables_blocklist.sh
          jq -r '.data[][1] | "iptables -A INPUT -s \(.) -j DROP"' data.json >> iptables_blocklist.sh
          chmod +x iptables_blocklist.sh
          echo "Generated iptables_blocklist.sh"
          jq -r '.data[] | select(.[2] == 22) | .[1]' data.json > port_22_ssh.txt
          echo "Generated port_22_ssh.txt"
          jq -r '.data[] | select(.[2] == 3389) | .[1]' data.json > port_3389_rdp.txt
          echo "Generated port_3389_rdp.txt"
          echo "ASN,Organization,IP_Count" > asn_summary.csv
          jq -r '.data[] | [.[10], .[11]] | @csv' data.json | sort | uniq -c | sort -nr | sed -E 's/^[ ]*([0-9]+)[ ]+(.*)$/\2,\1/' >> asn_summary.csv
          echo "Generated asn_summary.csv"

      # Step 3: Generate Charts
      - name: Generate Statistics and Charts
        run: | # <-- FIX: Added pipe for multi-line script. This is the main source of the errors.
          echo "Generating charts from data..."

          # 1. Top 10 ISPs Chart
          # Using index 12 for ISP, as per the CSV header
          ISP_DATA=$(jq -r '.data[][12]? | select(. != null and . != "")' data.json | sort | uniq -c | sort -nr | head -n 10)
          
          if [ -z "$ISP_DATA" ]; then echo "No ISP data found, skipping chart."; else
            ISP_LABELS=$(echo "$ISP_DATA" | awk '{$1=""; print $0}' | sed 's/^ *//' | jq -R . | jq -s .)
            ISP_VALUES=$(echo "$ISP_DATA" | awk '{print $1}' | jq -s .)
            ISP_CHART_CONFIG=$(cat <<EOF
            {type:'bar',data:{labels:$ISP_LABELS,datasets:[{label:'Top 10 ISPs',backgroundColor:'rgba(54, 162, 235, 0.5)',borderColor:'rgb(54, 162, 235)',borderWidth:1,data:$ISP_VALUES}]},options:{indexAxis:'y',plugins:{legend:{display:false}},title:{display:true,text:'Top 10 ISPs by Entry Count'}}}
EOF
            )
            ENCODED_ISP_CHART=$(echo "$ISP_CHART_CONFIG" | jq -c . | curl -s -X POST -H "Content-Type: application/json" -d @- "https://quickchart.io/chart/create" | jq -r .url)
            curl -s -o isp_chart.png "$ENCODED_ISP_CHART"
          fi

          # 2. Protocol Distribution Chart
          PROTOCOL_DATA=$(jq -r '.data[][7]? | select(. != null and . != "")' data.json | sort | uniq -c | sort -nr)
          
          if [ -z "$PROTOCOL_DATA" ]; then echo "No Protocol data found, skipping chart."; else
            PROTOCOL_LABELS=$(echo "$PROTOCOL_DATA" | awk '{$1=""; print $0}' | sed 's/^ *//' | jq -R . | jq -s .)
            PROTOCOL_VALUES=$(echo "$PROTOCOL_DATA" | awk '{print $1}' | jq -s .)
            PROTOCOL_CHART_CONFIG=$(cat <<EOF
            {type:'pie',data:{labels:$PROTOCOL_LABELS,datasets:[{data:$PROTOCOL_VALUES}]},options:{plugins:{piechartOutlabels:{text:'%l %p',color:'white',stretch:35,font:{resizable:true,minSize:12,maxSize:18}}},title:{display:true,text:'Protocol Distribution'}}}
EOF
            )
            ENCODED_PROTOCOL_CHART=$(echo "$PROTOCOL_CHART_CONFIG" | jq -c . | curl -s -X POST -H "Content-Type: application/json" -d @- "https://quickchart.io/chart/create" | jq -r .url)
            curl -s -o protocol_chart.png "$ENCODED_PROTOCOL_CHART"
          fi

          # 3. TCP vs UDP Chart
          TYPE_DATA=$(jq -r '.data[][7]? | select(. != null and . != "")' data.json | grep -E '^(TCP|UDP)$' | sort | uniq -c | sort -nr)
          
          if [ -z "$TYPE_DATA" ]; then echo "No TCP/UDP data found, skipping chart."; else
            TYPE_LABELS=$(echo "$TYPE_DATA" | awk '{$1=""; print $0}' | sed 's/^ *//' | jq -R . | jq -s .)
            TYPE_VALUES=$(echo "$TYPE_DATA" | awk '{print $1}' | jq -s .)
            TYPE_CHART_CONFIG=$(cat <<EOF
            {type:'doughnut',data:{labels:$TYPE_LABELS,datasets:[{data:$TYPE_VALUES,backgroundColor:['rgb(255, 99, 132)','rgb(54, 162, 235)']}]},options:{title:{display:true,text:'TCP vs. UDP'}}}
EOF
            )
            ENCODED_TYPE_CHART=$(echo "$TYPE_CHART_CONFIG" | jq -c . | curl -s -X POST -H "Content-Type: application/json" -d @- "https://quickchart.io/chart/create" | jq -r .url)
            curl -s -o type_chart.png "$ENCODED_TYPE_CHART"
          fi
          echo "Chart generation step completed."

      # Step 4: Update README
      - name: Update README count
        run: | # <-- FIX: Added pipe for multi-line script
          IP_COUNT=$(wc -l < ip_list.txt | awk '{print $1}')
          COUNT_FORMATTED=$(printf "%'d" $IP_COUNT)
          BADGE_URL="https://img.shields.io/badge/IPs%20Tracked-${COUNT_FORMATTED}-blue?style=for-the-badge"
          sed -i "s|<!-- IP_COUNT_PLACEHOLDER -->.*|<!-- IP_COUNT_PLACEHOLDER -->\n\n![IPs Tracked](${BADGE_URL})|g" README.md

      # Step 5: Commit and Push
      - name: Commit and push changes
        run: | # <-- FIX: Added pipe for multi-line script
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Update: Fetched latest data and regenerated all formats"
            git push
          else
            echo "No changes to commit. Data is up-to-date."
          fi
